### PR TITLE
Header only parsing.

### PR DESCRIPTION
**Pull request by constellates**
Hi, I'm using the nifti-js library for a project where I only need to parse the header contents. So far to do this I have added a new module export "parseHeader" which duplicates a lot of the functionality in the original "parse" and formats the output more along the lines of the nifti specification naming conventions. 

Are you interested in incorporating this functionality into this library? If so I can make some more changes so we're not duplicating header parsing code between the two parse functions.

### CODE REVIEW

**Comment by jaspervdg** [comment]
Hi, thanks for your efforts! I am also wondering why you actually need a separate function, as the original parse function should in fact also be able to deal with header-only files (if it can't this is a bug). If for some reason you really need the Nifti naming conventions, I would suggest splitting the original parse function into two parts (basically where it says "Convert to NRRD-compatible structure"). However, note that the NRRD ones seem to be a bit more future proof/systematic, so I chose to make both modules use those in the interest of interoperability.

**Comment by constellates** [comment]
I was having trouble getting it to only parse the header of a file. I was trying to use it in the following example. Note I'm using fs in node to read the first 270 bytes of a gzipped nifti which then gets uncompressed to the full 348 byte header size.

```
/**
 * Read Nifti Header
 *
 * Takes a file and returns a json parsed nifti
 * header without reading any extra bytes.
 */
function readNiftiHeader (file, callback) {
    fs.open(file.path, 'r', function(status, fd) {
        if (status) {
            console.log(status.message);
            return;
        }
        var buffer = new Buffer(270);
        fs.read(fd, buffer, 0, 269, 0, function (err, num){
            var unzipped = zlib.gunzipSync(buffer);
            callback(nifti.parse(unzipped));
        });
    });
}
```

With this setup it was throwing this error from inside "parseNIfTIRawData"

```
function checkSize(sizeOfType) {
    if (buffer.byteLength<totalLen*sizeOfType) throw new Error("NIfTI file does not contain enough data!")
}
```

With regards to the NIfTI vs NRRD formatting, I wasn't aware of NRRD. I'm working on a tool for validating a package of files including NIfTIs. For now I just need the repetition time value and unit (spacings[4]  and spaceUnits[4]) so NRRD should work for now. However it appears that NRRD formatting leaves out a handful of values that are defined on the NIfTI header. I'm not sure at this point but these values could become important to what I'm doing in the future.

**Comment by jaspervdg** [comment]
Could you check whether the header ends with "ni1" or "n+1"? The error you are describing suggests the header ends with "n+1", which is supposed to indicate that the data should be included in the file (which it obviously is not, hence the error). If the header does end with "ni1", or if you're not quite sure what to look for, could you post the header here?

Also, NRRD has some room for storing "extra" stuff, and I may not even have exhausted all regular possibilities yet, so if you are missing some specific values it would be interesting to know which ones, so we can see what the best way would be to add them. Ultimately, if it turns out to be hard to map those properties to NRRD, we could still split up parsing in a Nifti-specific part and a conversion to NRRD part (it is already set up more or less like this anyway).

**Comment by constellates** [comment]
If I log the magic string right before the check it is equal to "n+1" so I assume that's the end of the header you're mentioning. Here's a link to the nifti file I'm currently testing with. https://drive.google.com/a/squishymedia.com/file/d/0B2JWN60ZLkgkSlhDOXFkRHBqVUk/view

I also would like to check that I understand this correctly. Does the header contain an indicator value as to whether or not the file is only a header or contains full file contents?

If that's the case I'm guessing the error is caused by my use case of wanting parse only the header of files that contain full file contents. With the intention being to not lose performance by reading and parsing content I don't need. And if this is the case would you prefer to split header parsing as it's own method or pass another argument to specify if it's header only data?

With regards to what's missing from the NRRD output I am just referencing this write up about the format http://brainder.org/2012/09/23/the-nifti-file-format/ . So far everything I need is in the NRRD output, but I'll let you know if in the future other values become important.

**Comment by jaspervdg** [comment]
Yes, the header contains an indication of whether or not the file also includes the data or not ("n+1" indicates that data will follow). I think for Nifti it might indeed make sense to split up the functionality. My suggestion would be to have a method that "just" parses a Nifti header (and returns values in its "native" format), a method that converts that to NRRD conventions, and a method that loads/parses a file (the current parse function) that wraps those two, and would be the usual point of entry. Does this sound reasonable?

**Comment by constellates** [comment]
That sounds good to me. Take a look, I've updated this branch with the changes you mentioned. I did also change some formatting / structural changes and made some fixes to ensure it passes jshint.

The main changes are to the following methods

```
parse
parseHeader
NIfTIToNRRD
parseBody
```

Parse should still return the exact same structure as before these changes, but is now created by calling the other methods.

 Let me know if you have any question or concerns about these changes and any naming conventions.

**Comment by jaspervdg** [comment]
In general, please try to stick to the existing conventions when submitting a pull request, especially since we try to be somewhat consistent within scijs. If you feel the conventions need to be changed, please raise this as a separate issue. In the end, I decided to first do a very basic refactor, also giving me a chance to update the nifti-js repository to the current scijs conventions. If anything is missing in the current refactor (which is quite possible, as I literally just split up the old parse function and exposed some of the functionality separately), I would welcome any pull requests based on the current head.

**Comment by constellates** [comment]
I just ran some tests again and your update works with my needs. Can you publish this version to npm. (looks like it's currently at 0.0.0 on npm). Thank you for the update and for being super responsive.

**Comment by jaspervdg** [comment]
It is now published (just wanted to wait and see whether this change worked for you).

**Pull request closed without merging**
